#pragma config(Sensor, in1,    powerExpander,  sensorAnalog)
#pragma config(Sensor, in8,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  quadLeft,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  bump,           sensorTouch)
#pragma config(Sensor, dgtl4,  limit,          sensorTouch)
#pragma config(Sensor, dgtl5,  LEDgreen,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  LEDyellow,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  LEDred,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  jumper,         sensorTouch)
#pragma config(Sensor, dgtl11, quadRight,      sensorQuadEncoder)
#pragma config(Motor,  port2,           leftCLift,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftMGLift,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           drvToolLeft,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           drvBottomLeft, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           drvBottomRight, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           drvTopRight,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightMGLift,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightCLift,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          claw,          tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{



}
